import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/components/header";
import GeometricBackground from "@/components/geometric-background";
import { ProtectedRouteProvider } from "@/provider/protected-route-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //     <body
    //       className={`${geistSans.variable} ${geistMono.variable} antialiased bg-green-600 dark:bg-green-500`}
    //     >
    <ProtectedRouteProvider>
      <div className="relative min-h-screen overflow-hidden">
        {/* Geometric Background */}
        <GeometricBackground />

        {/* Main Content Card */}
        <div className="relative mx-auto my-8 h-0 min-h-[calc(100vh-4rem)] max-w-6xl overflow-hidden rounded-3xl bg-white/95 shadow-2xl backdrop-opacity-80">
          {/* Navigation */}
          <Header />
          {children}
        </div>
      </div>
    </ProtectedRouteProvider>
    //     </body>
    // </html>
  );
}
