import type { Metadata } from "next";
import { PrivateRouteProvider } from "@/provider/private-route-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <PrivateRouteProvider>{children}</PrivateRouteProvider>;
}
