import type { Metadata } from "next";
import { Geist, Geist_Mono, Delius_Unicase } from "next/font/google";
import "@/app/globals.css";
import ReactQueryProvider from "@/provider/react-query-provider";
import AuthProvider from "@/provider/auth-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const deliusUnicase = Delius_Unicase({
  variable: "--font-delius-unicase",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Super Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${deliusUnicase.variable} antialiased`}
      >
        <Toaster className="bg-purple-600"/>
        <ReactQueryProvider>
          <AuthProvider>{children}</AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
